version: '3.8'

services:
  django:
    build: .
    environment:
      SECRET_KEY: 26d9cc0237d3beb9732dfdc6a546a256
      DEBUG: true
      DATABASE_URL: postgres://postgres:postgres@postgres/postgres
    tty: true
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - '3000:8000'
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: pg_isready -U postgres
      interval: 3s
    ports:
      - "5432:5432"
