version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    environment:
      DEBUG: true
      SECRET_KEY: k$b$wb7mi=!%4n^m!r8h%z$hv*8p=&^^d%x4#saz9v29b6#0ww
      DATABASE_URL: postgres://postgres:postgres@postgres/postgres
    tty: true
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: pg_isready -U postgres
      interval: 3s
    ports:
      - '5432:5432'
